#===============================================================================
# APP Configuration file
#===============================================================================


#===============================================================================
# DATASOURCES
#===============================================================================
data.hostname: "127.0.0.1"
data.port: 9000
dataset: "/home/gmarciani/Workspace/crimegraph/data/dataset.txt"

#===============================================================================
# NEO4J
#===============================================================================
neo4j.hostname: "bolt://localhost:7687"
neo4j.username: "neo4j"
neo4j.password: "password"

