#===============================================================================
# APP Configuration file
#===============================================================================

#===============================================================================
# Boolean settings
#===============================================================================
propertyBoolean: False

#===============================================================================
# String settings
#===============================================================================
propertyString: "Default"

#===============================================================================
# Path settings
#===============================================================================
propertyPath: !resolveString "${RES}/sample.txt"

#===============================================================================
# Object settings
#===============================================================================
propertyObject:
  a: 10
  b: "SECONDS"