#===============================================================================
# APP Configuration file
#===============================================================================

#===============================================================================
# Boolean settings
#===============================================================================
propertyBoolean: True

#===============================================================================
# String settings
#===============================================================================
propertyString: "Custom"

#===============================================================================
# Path settings
#===============================================================================
propertyPath: !resolveString "${RES}/sample.txt"

#===============================================================================
# Object settings
#===============================================================================
propertyObject:
  a: 1
  b: "MINUTES"