#===============================================================================
# CRIMEGRAPH Configuration file
#===============================================================================

#===============================================================================
# INPUT
#===============================================================================
dataset: "resources/crimegraph/data/crimegraph.data"

#===============================================================================
# OUTPUT
#===============================================================================
output: "resources/crimegraph/out/crimegraph.out"

#===============================================================================
# LINK DETECTION
#===============================================================================
hidden.metric: "local"
hidden.threshold: 0.5

#===============================================================================
# LINK PREDICTION
#===============================================================================
potential.metric: "local"
potential.locality: 1
potential.weight: [1.0]
potential.threshold: 0.5

#===============================================================================
# NEO4J
#===============================================================================
neo4j.hostname: "bolt://localhost:7687"
neo4j.username: "neo4j"
neo4j.password: "password"