---
# file: app/vars/main.yml
app_main: /vagrant/site/app.js
app_port: 3333

flink_port: 8081
neo4j_http_port: 7474
neo4j_bolt_port: 7687
neo4j_username: neo4j
neo4j_password: password

node_home: /opt/node-v6.10.0-linux-x64
