---
# file: nodejs/tasks/main.yml
- name: check Node.js (binary)
  stat:
    path: "{{ node_home }}/bin/node"
  register: nodeBin

- name: download node
  get_url:
    url: "{{ node_download }}"
    dest: "{{ node_archive_path }}"
  when: not nodeBin.stat.exists

- name: check node (archive)
  stat:
    path: "{{ node_archive_path }}"
  register: nodeArchive

- name: unarchive node
  unarchive:
    src: "{{ node_archive_path }}"
    dest: "{{ node_home | dirname }}"
    remote_src: True
    mode: 755
  when: nodeArchive.stat.exists

- name: remove archive node
  file:
    path: "{{ node_archive_path }}"
    state: absent

- name: configure permissions for node
  file:
    path: "{{ node_home }}/bin/{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
    - name: node
      mode: 775

- name: update alternatives node
  alternatives:
    name: "{{ item }}"
    path: "{{ node_home }}/bin/{{ item }}"
    link: "/usr/bin/{{ item }}"
    priority: 100
  with_items:
    - node
    - npm

- name: configure envars node
  lineinfile:
    name: /etc/profile.d/crimegraph-env.sh
    regexp: "^NODE_HOME="
    line: "NODE_HOME={{ node_home }}"
    state: present
    insertbefore: BOF
    create: yes
