---
# file: nginx/tasks/main.yml
- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Configure nginx site default
  template:
    src: default.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx
