---
# file: playbook.yml
- name: common configuration
  hosts: all
  remote_user: admin
  become: true
  roles:
    - common
    - ec2
    - java

- name: provision kafka nodes
  hosts: kafka
  remote_user: admin
  become: true
  roles:
    - kafka

- name: provision flink nodes
  hosts: flink
  remote_user: admin
  become: true
  roles:
    - flink
    - flink-app

- name: provision neo4j nodes
  hosts: neo4j
  remote_user: admin
  become: true
  roles:
    - neo4j
